  name: Periodic Workflow
  on:
    schedule:
        - cron '*/30 19 * * 2'
  jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - run: echo ${{ github.repository }}
            - run: echo ${{ github.repository_owner }}
            - run: echo ${{ runner.os }}
            - run: echo ${{ github.event_name }}
            - run: echo ${{ github.workflow }}
            - run: echo ${{ github.run_attempt }}